#.github/workflows/scheduled-run.yml
name:  Run test.py on push

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Write file to known location
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
