name: Example

on: push

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - run: echo -n -e "HELLO\n !\n World!" > textv.txt

    - uses: pCYSl5EDgo/cat@master
      id: hello
      with:
        path: textv.txt

    - run: echo $TEXT
      env:
        TEXT: ${{ steps.hello.outputs.textv }}